### ISSUE TITLE
Typo when creating model versions

### ISSUE THREAD

**Issue by dgarijo** [mintproject/MINT-ModelCatalogAPI-client#4]
The following error was reported by Min Yin:

I ran into an error when try to create a model version:

Traceback (most recent call last):
  File "mintcient.py", line 83, in <module>
    api_instance.create_model_version(model_version)
AttributeError: 'ModelApi' object has no attribute 'create_model_version'

Here is the code snippet:

###################################

# Create a model version
model_version = {
  "hasConfiguration": [
    {
      "id": "sscyp_generate_histogram"
    }
  ],
  "hasVersionId": "1.0",
  "id": "SSCYP_1.0",
  "label": "SSCYP v1.0",
  "type": [
    "http://ontosoft.org/software#SoftwareVersion"
  ]
}

# Create a ModelVersion
api_instance = mint_client.ModelApi(mint_client.ApiClient(configuration))
try:
    api_instance.create_model_version(model_version)
    pprint("Created")
except ApiException as e:
    print("Exception: %s\n" % e)
######################################

**Comment by sirspock** [comment]
Fixed in the last version of the notebook
