### ISSUE TITLE
Enhance CRUD Operations

### ISSUE THREAD

**Issue by brandomr** [mintproject/MINT-ModelCatalogAPI-client#5]
# Overview
Users need a way to `UPDATED` and `DELETE` the models, versions, configurations, datasets, and parameters which they create in the model catalog. 

Since correct registration of these in MINT can be complex and difficult, it is necessarily an iterative process. Therefore, to reduce duplication and enable flexibility as our understanding of a model/configuration/etc. changes, it is important that a user is able to update or delete records in their namespace in the MINT Catalog.

- [x] Update paths
- [x] Delete paths

**Comment by dgarijo** [comment]
We will implement updates through puts, initially.

**Comment by sirspock** [comment]
I added the put and delete method
