### ISSUE TITLE
Keyword search for models

### ISSUE THREAD

**Issue by brandomr** [mintproject/MINT-ModelCatalogAPI-client#6]
# Overview
Users need a way to search for models based on words contained in the model name, description, category, or parameters so that they can identify models that are relevant to their specific use cases.

Users should be able to execute case-insensitive exact and fuzzy searches, using a standard such as Lucene query syntax or by simply providing a wildcard card character (`*`).

**Comment by dgarijo** [comment]
This type of functionality is not within of the scope of this API at the moment. This API is for access, edit and insert new data in the model catalog.

We have implemented a search bar in https://models.mint.isi.edu/ by retrieving the label of models and then doing an autocomplete through javascript. This approach will scale until we have thousands of models, so it's enough at the moment

**Comment by dgarijo** [comment]
I will keep this issue open as it could be interesting to tackle if we have the time

**Comment by dgarijo** [comment]
Search queries have been added to: https://query.mint.isi.edu/api/mintproject/MINT-ModelCatalogQueries#/ 
You just need to send a text to match and you will get some results. You can test in the link above. I will close this issue, for the moment, please reopen if there are further questions.
